#!/usr/bin/env python3
"""Convert npow/airline-codes JSON to a compact PROGMEM lookup header.

Build logic mirrors plane-tracker-rgb-pi/its-a-plane-python/utilities/airlines.py
(source array, not the flattened cache which corrupts duplicate IATA codes).
"""

from __future__ import annotations

import argparse
import json
import re
import urllib.request
from pathlib import Path

NPOW_URL = "https://raw.githubusercontent.com/npow/airline-codes/master/airlines.json"

ICAO_CODE = re.compile(r"^[A-Z]{3}$")
IATA_CODE = re.compile(r"^[A-Z]{2}$")

# Regional / brand overrides (mirrors utilities/airlines.py)
OVERRIDES = {
    "ENY": "American Eagle",
    "JIA": "American Eagle",
    "PDT": "American Eagle",
    "PSA": "American Eagle",
    "GJS": "United Express",
    "CPZ": "United Express",
    "ASH": "United Express",
    "G7": "United Express",
    "UCA": "United Express",
    "EDV": "Delta Connection",
    "ASQ": "Delta Connection",
    "RPA": "Republic Airways",
    "SKW": "SkyWest Airlines",
    "QXE": "Horizon Air",
    "TIV": "Thrive Aviation",
}

# Junk / placeholder ICAO codes in OpenFlights-derived data
ICAO_BLOCKLIST = frozenset(
    {
        "ZZZ",
        "XXX",
        "000",
        "001",
        "666",
        "770",
        "99F",
        "???",
        "***",
        "---",
        "...",
        ":::",
        "===",
        "??!",
    }
)

MAX_NAME_LEN = 28


def fetch_npow_records() -> list[dict]:
    with urllib.request.urlopen(NPOW_URL, timeout=60) as resp:
        return json.loads(resp.read().decode("utf-8"))


def load_records(path: Path | None) -> list[dict]:
    if path is not None and path.is_file():
        raw = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(raw, list):
            return raw
    return fetch_npow_records()


def build_tables(records: list[dict]) -> tuple[dict[str, str], dict[str, str]]:
    """Return (icao_map, iata_map) with correct per-record pairing."""
    icao_map: dict[str, str] = {}
    iata_map: dict[str, str] = {}

    def is_active(record: dict) -> bool:
        return (record.get("active") or "").upper() == "Y"

    # Active airlines first so they win duplicate IATA codes (e.g. OZ → Asiana).
    ordered = sorted(records, key=lambda r: (not is_active(r), r.get("id", "")))

    for record in ordered:
        name = (record.get("name") or "").strip()
        icao = (record.get("icao") or "").strip().upper()
        iata = (record.get("iata") or "").strip().upper()
        if not name or name == "Private flight":
            continue
        if not is_active(record):
            continue

        display = OVERRIDES.get(icao, name)[:MAX_NAME_LEN]

        if (
            icao
            and icao != "N/A"
            and ICAO_CODE.match(icao)
            and icao[0].isalpha()
            and icao not in ICAO_BLOCKLIST
        ):
            icao_map[icao] = OVERRIDES.get(icao, display)

        if iata and iata != "-" and IATA_CODE.match(iata) and iata[0].isalpha():
            if iata not in iata_map:
                iata_map[iata] = display

    for code, name in OVERRIDES.items():
        if len(code) == 3 and ICAO_CODE.match(code):
            icao_map[code] = name[:MAX_NAME_LEN]
        elif len(code) == 2 and IATA_CODE.match(code):
            iata_map[code] = name[:MAX_NAME_LEN]

    return icao_map, iata_map


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        default=None,
        help="Optional npow JSON array; default downloads from GitHub",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path(__file__).parent.parent / "include" / "data" / "airlines_lookup.h",
    )
    args = parser.parse_args()

    records = load_records(args.input)
    icao_map, iata_map = build_tables(records)
    icao_entries = sorted(icao_map.items())
    iata_entries = sorted(iata_map.items())

    names: list[str] = []
    name_index: dict[str, int] = {}

    def pool_offset(name: str) -> int:
        name = name[:MAX_NAME_LEN]
        if name not in name_index:
            name_index[name] = sum(len(n) + 1 for n in names)
            names.append(name)
        return name_index[name]

    icao_rows = [
        f'  {{ "{code}", {pool_offset(name)} }},' for code, name in icao_entries
    ]
    iata_rows = [
        f'  {{ "{code}", {pool_offset(name)} }},' for code, name in iata_entries
    ]
    names_blob = "".join(f'  "{c_escape(n)}\\0"\n' for n in names)

    header = f"""#pragma once
// Auto-generated by tools/airlines_to_header.py — do not edit.
// Active airlines from npow/airline-codes ({len(icao_entries)} ICAO, {len(iata_entries)} IATA).

#include <cstddef>
#include <cstdint>

namespace data::airlines {{

constexpr size_t kIcaoCount = {len(icao_entries)};
constexpr size_t kIataCount = {len(iata_entries)};
constexpr size_t kMaxNameLen = {MAX_NAME_LEN};

struct Entry {{
  char code[4];
  uint32_t name_offset;
}};

extern const char kNames[];
extern const Entry kIcao[kIcaoCount];
extern const Entry kIata[kIataCount];

}}  // namespace data::airlines
"""

    cpp = f"""// Auto-generated by tools/airlines_to_header.py — do not edit.
#include "data/airlines_lookup.h"

#include <pgmspace.h>

namespace data::airlines {{

const char kNames[] PROGMEM =
{names_blob};

const Entry kIcao[kIcaoCount] PROGMEM = {{
{chr(10).join(icao_rows)}
}};

const Entry kIata[kIataCount] PROGMEM = {{
{chr(10).join(iata_rows)}
}};

}}  // namespace data::airlines
"""

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="utf-8")
    cpp_path = args.output.parent.parent.parent / "src" / "data" / "airlines_lookup.cpp"
    cpp_path.parent.mkdir(parents=True, exist_ok=True)
    cpp_path.write_text(cpp, encoding="utf-8")
    print(f"Wrote {args.output} and {cpp_path}")
    print(f"  ICAO {len(icao_entries)}, IATA {len(iata_entries)}, unique names {len(names)}")
    print(f"  Sample: AAL={icao_map.get('AAL','?')} OZ(IATA)={iata_map.get('OZ','?')} AAR={icao_map.get('AAR','?')}")


if __name__ == "__main__":
    main()
