#!/usr/bin/env python3
"""Build ICAO type designator -> description tables for PROGMEM lookup.

Default source: tar1090-db aircraft.csv.gz (Mictronics registration DB).
Extracts the most common long type name per ICAO designator (e.g. E75L).
"""

from __future__ import annotations

import argparse
import gzip
import re
import sys
import urllib.error
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path

TAR1090_CSV_URL = (
    "https://raw.githubusercontent.com/wiedehopf/tar1090-db/csv/aircraft.csv.gz"
)

ICAO_TYPE = re.compile(r"^[A-Z0-9]{2,4}$")
MAX_NAME_LEN = 56


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def cache_path() -> Path:
    return Path(__file__).resolve().parent / ".cache" / "aircraft.csv.gz"


def default_header_path() -> Path:
    return repo_root() / "include" / "data" / "icao_types_lookup.h"


def default_cpp_path() -> Path:
    return repo_root() / "src" / "data" / "icao_types_lookup.cpp"


def normalize_name(name: str) -> str:
    """Mictronics uses ALL CAPS; keep model text, title-case manufacturer."""
    name = " ".join(name.split())
    if not name:
        return name
    parts = name.split(None, 1)
    if len(parts) == 1:
        return parts[0].capitalize()
    return f"{parts[0].capitalize()} {parts[1]}"


def download_csv(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url, timeout=120) as resp:
        data = resp.read()
    dest.write_bytes(data)


def load_csv_text(path: Path) -> str:
    raw = path.read_bytes()
    if path.suffix == ".gz" or raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    return raw.decode("utf-8", errors="replace")


def build_map_from_csv(text: str) -> dict[str, str]:
    counts: dict[str, Counter[str]] = defaultdict(Counter)
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split(";")
        if len(parts) < 5:
            continue
        code = parts[2].strip().upper()
        name = normalize_name(parts[4].strip())
        if not ICAO_TYPE.match(code) or not name:
            continue
        counts[code][name[:MAX_NAME_LEN]] += 1

    return {
        code: counter.most_common(1)[0][0]
        for code, counter in counts.items()
        if counter
    }


def c_pool_bytes(names: list[str]) -> str:
    tokens: list[str] = []
    for name in names:
        for byte in name.encode("utf-8"):
            tokens.append(f"0x{byte:02x}")
        tokens.append("0x00")
    lines: list[str] = []
    for i in range(0, len(tokens), 16):
        lines.append("  " + ", ".join(tokens[i : i + 16]) + ",")
    return "\n".join(lines)


def write_outputs(type_map: dict[str, str], header_path: Path, cpp_path: Path) -> None:
    entries = sorted(type_map.items())

    names: list[str] = []
    name_index: dict[str, int] = {}

    def pool_offset(name: str) -> int:
        clipped = name[:MAX_NAME_LEN]
        if clipped not in name_index:
            name_index[clipped] = sum(len(n.encode("utf-8")) + 1 for n in names)
            names.append(clipped)
        return name_index[clipped]

    rows = [f'  {{ "{code}", {pool_offset(name)} }},' for code, name in entries]
    names_blob = c_pool_bytes(names)

    header = f"""#pragma once
// Auto-generated by tools/icao_types_to_header.py — do not edit.
// ICAO aircraft type designators ({len(entries)} entries).
// Source: wiedehopf/tar1090-db aircraft.csv.gz (Mictronics).

#include <cstddef>
#include <cstdint>

namespace data::icao_types {{

constexpr size_t kCount = {len(entries)};
constexpr size_t kMaxNameLen = {MAX_NAME_LEN};

struct Entry {{
  char code[5];
  uint16_t name_offset;
}};

extern const char kNames[];
extern const Entry kTypes[kCount];

}}  // namespace data::icao_types
"""

    cpp = f"""// Auto-generated by tools/icao_types_to_header.py — do not edit.
#include "data/icao_types_lookup.h"

#include <pgmspace.h>

namespace data::icao_types {{

const char kNames[] PROGMEM = {{
{names_blob}
}};

const Entry kTypes[kCount] PROGMEM = {{
{chr(10).join(rows)}
}};

}}  // namespace data::icao_types
"""

    header_path.parent.mkdir(parents=True, exist_ok=True)
    cpp_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(header, encoding="utf-8")
    cpp_path.write_text(cpp, encoding="utf-8")


def outputs_exist(header_path: Path, cpp_path: Path) -> bool:
    return header_path.is_file() and cpp_path.is_file()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        default=None,
        help="Optional local aircraft.csv or aircraft.csv.gz",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=default_header_path(),
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Do not download; use --input, cache, or fail",
    )
    args = parser.parse_args()

    header_path = args.output
    cpp_path = default_cpp_path()
    cached = cache_path()

    csv_path: Path | None = args.input
    if csv_path is None and not args.offline:
        try:
            print(f"icao_types: downloading {TAR1090_CSV_URL}")
            download_csv(TAR1090_CSV_URL, cached)
            csv_path = cached
        except (OSError, urllib.error.URLError) as exc:
            print(f"icao_types: download failed ({exc})")
            if cached.is_file():
                print(f"icao_types: using cached {cached}")
                csv_path = cached
    elif csv_path is None and cached.is_file():
        csv_path = cached

    if csv_path is None or not csv_path.is_file():
        if outputs_exist(header_path, cpp_path):
            print("icao_types: keeping existing generated lookup files")
            return 0
        print("icao_types: no input and no existing generated files", file=sys.stderr)
        return 1

    type_map = build_map_from_csv(load_csv_text(csv_path))
    if not type_map:
        print("icao_types: no type entries parsed", file=sys.stderr)
        return 1

    write_outputs(type_map, header_path, cpp_path)
    print(f"Wrote {header_path} and {cpp_path}")
    print(f"  Types {len(type_map)}")
    print(
        "  Sample: "
        f"B738={type_map.get('B738', '?')} "
        f"B38M={type_map.get('B38M', '?')} "
        f"E75L={type_map.get('E75L', '?')}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
